package com.shreyash.sensorapp.presentation.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006494)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFC9E6FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001E30)
val md_theme_light_secondary = Color(0xFF4F616E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD2E5F5)
val md_theme_light_onSecondaryContainer = Color(0xFF0C1D29)
val md_theme_light_surface = Color(0xFFFDFCFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFDEE3E8)
val md_theme_light_onSurfaceVariant = Color(0xFF42474C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)

val md_theme_dark_primary = Color(0xFF8BCBFF)
val md_theme_dark_onPrimary = Color(0xFF00344C)
val md_theme_dark_primaryContainer = Color(0xFF004B6E)
val md_theme_dark_onPrimaryContainer = Color(0xFFC9E6FF)
val md_theme_dark_secondary = Color(0xFFB6C9D9)
val md_theme_dark_onSecondary = Color(0xFF21323E)
val md_theme_dark_secondaryContainer = Color(0xFF384955)
val md_theme_dark_onSecondaryContainer = Color(0xFFD2E5F5)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE2E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF42474C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C7CC)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)

val SensorGreen = Color(0xFF4CAF50)
